"""
Loads model_weights_2.pth (trained by train_iteration2.py) and generates
C headers containing:
  1. int8-quantized weight matrices + float32 biases / LayerNorm params
  2. character <-> id tokenizer tables (UTF-8 aware for the 14 non-ASCII chars)

The C code that consumes these headers lives in ../firmware/ and can also
be linked into ../host_test/ for verification on the developer machine.

Quantization scheme (weight-only, per-tensor symmetric):
    scale     = max(|W|) / 127.0
    W_int8    = round(W / scale)                        clipped to [-127, 127]
    W_float   = W_int8 * scale                          (at inference time)

Biases and LayerNorm gamma / beta remain float32 -- they are small and
accumulate the int8 x float MACs, so keeping them in higher precision
avoids error blow-up while barely affecting flash usage.
"""

import os
import sys
from pathlib import Path

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
WEIGHTS_PATH = Path(__file__).resolve().parents[1] / "model_weights_2.pth"
CORPUS_PATH = REPO_ROOT / "TinyStories-valid.txt"
OUT_DIR = Path(__file__).resolve().parents[1] / "firmware" / "generated"

VOCAB_SIZE = 98
CONTEXT_LENGTH = 64
EMBED_DIM = 128
NUM_HEADS = 2
HEAD_DIM = EMBED_DIM // NUM_HEADS
FF_DIM = EMBED_DIM * 2


def quantize_int8(tensor: torch.Tensor):
    """Per-tensor symmetric int8 quantization. Returns (int8_array, scale)."""
    w = tensor.detach().to(torch.float32).cpu().numpy()
    max_abs = float(abs(w).max())
    if max_abs == 0.0:
        return w.astype("int8"), 0.0
    scale = max_abs / 127.0
    q = (w / scale).round().clip(-127, 127).astype("int8")
    return q, scale


def emit_int8_array(name: str, arr, dims):
    """Emit `const int8_t name[dims...] = { ... };` (row-major)."""
    flat = arr.reshape(-1)
    dims_str = "".join(f"[{d}]" for d in dims)
    lines = [f"const int8_t {name}{dims_str} = {{"]
    row_len = dims[-1]
    for i in range(0, flat.size, row_len):
        chunk = ", ".join(str(int(v)) for v in flat[i : i + row_len])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_float_array(name: str, arr, dims):
    flat = arr.reshape(-1)
    dims_str = "".join(f"[{d}]" for d in dims)
    lines = [f"const float {name}{dims_str} = {{"]
    row_len = dims[-1] if dims else flat.size
    for i in range(0, flat.size, row_len):
        chunk = ", ".join(f"{float(v):.8g}f" for v in flat[i : i + row_len])
        lines.append("    " + chunk + ",")
    lines.append("};")
    return "\n".join(lines)


def emit_scale(name: str, scale: float) -> str:
    return f"const float {name} = {scale:.8g}f;"


def build_weights_header(state):
    """Return the text of model_weights.h."""
    out = [
        "/* Auto-generated by tools/quantize.py -- do not edit. */",
        "#ifndef MODEL_WEIGHTS_H",
        "#define MODEL_WEIGHTS_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    # --- Embeddings -----------------------------------------------------
    for name, dims in [
        ("char_embedding", (VOCAB_SIZE, EMBED_DIM)),
        ("pos_embedding", (CONTEXT_LENGTH, EMBED_DIM)),
    ]:
        w = state[f"{name}.weight"]
        q, s = quantize_int8(w)
        out.append(emit_int8_array(f"w_{name}", q, dims))
        out.append(emit_scale(f"s_{name}", s))
        out.append("")

    # --- Transformer layer weights -------------------------------------
    # Layer 1 uses the un-suffixed names; layer 2 uses "2" / "_2" suffixes,
    # matching train_iteration2.py.
    layers = [
        {  # layer index 0
            "q": ("query.weight", "query.bias"),
            "k": ("key.weight", "key.bias"),
            "v": ("value.weight", "value.bias"),
            "o": ("out_proj.weight", "out_proj.bias"),
            "ff1": ("ff1.weight", "ff1.bias"),
            "ff2": ("ff2.weight", "ff2.bias"),
            "n1": ("norm1.weight", "norm1.bias"),
            "n2": ("norm2.weight", "norm2.bias"),
        },
        {  # layer index 1
            "q": ("query2.weight", "query2.bias"),
            "k": ("key2.weight", "key2.bias"),
            "v": ("value2.weight", "value2.bias"),
            "o": ("out_proj2.weight", "out_proj2.bias"),
            "ff1": ("ff1_2.weight", "ff1_2.bias"),
            "ff2": ("ff2_2.weight", "ff2_2.bias"),
            "n1": ("norm3.weight", "norm3.bias"),
            "n2": ("norm4.weight", "norm4.bias"),
        },
    ]

    for i, m in enumerate(layers):
        for tag, (wk, bk), shape in [
            ("q", m["q"], (EMBED_DIM, EMBED_DIM)),
            ("k", m["k"], (EMBED_DIM, EMBED_DIM)),
            ("v", m["v"], (EMBED_DIM, EMBED_DIM)),
            ("o", m["o"], (EMBED_DIM, EMBED_DIM)),
            ("ff1", m["ff1"], (FF_DIM, EMBED_DIM)),
            ("ff2", m["ff2"], (EMBED_DIM, FF_DIM)),
        ]:
            q, s = quantize_int8(state[wk])
            out.append(emit_int8_array(f"w_l{i}_{tag}", q, shape))
            out.append(emit_scale(f"s_l{i}_{tag}", s))
            b = state[bk].detach().to(torch.float32).cpu().numpy()
            out.append(emit_float_array(f"b_l{i}_{tag}", b, (shape[0],)))
            out.append("")

        for tag, (wk, bk) in [("n1", m["n1"]), ("n2", m["n2"])]:
            gamma = state[wk].detach().to(torch.float32).cpu().numpy()
            beta = state[bk].detach().to(torch.float32).cpu().numpy()
            out.append(emit_float_array(f"ln_l{i}_{tag}_gamma", gamma, (EMBED_DIM,)))
            out.append(emit_float_array(f"ln_l{i}_{tag}_beta", beta, (EMBED_DIM,)))
            out.append("")

    # --- Output head ----------------------------------------------------
    q, s = quantize_int8(state["output_head.weight"])
    out.append(emit_int8_array("w_output_head", q, (VOCAB_SIZE, EMBED_DIM)))
    out.append(emit_scale("s_output_head", s))
    b = state["output_head.bias"].detach().to(torch.float32).cpu().numpy()
    out.append(emit_float_array("b_output_head", b, (VOCAB_SIZE,)))
    out.append("")

    out.append("#endif /* MODEL_WEIGHTS_H */")
    return "\n".join(out) + "\n"


def build_tokenizer_header(chars):
    """Emit an ASCII fast-path table plus a small multi-byte UTF-8 table.

    ASCII bytes get a direct 128-entry lookup returning the token id (or 255
    if the byte is not in vocabulary). Non-ASCII characters are encoded as
    UTF-8 (2-4 bytes) and matched against a small (id, byte-length, bytes[])
    table. There are only 14 non-ASCII chars in the vocab so this is tiny.

    For decoding, reverse_map[id] is a NUL-terminated UTF-8 string.
    """
    ascii_map = [255] * 128
    multi = []  # (id, utf8_bytes)
    for i, ch in enumerate(chars):
        b = ch.encode("utf-8")
        if len(b) == 1 and b[0] < 128:
            ascii_map[b[0]] = i
        else:
            multi.append((i, b))

    out = [
        "/* Auto-generated by tools/quantize.py -- do not edit. */",
        "#ifndef TOKENIZER_DATA_H",
        "#define TOKENIZER_DATA_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define VOCAB_SIZE      {len(chars)}",
        f"#define MULTI_BYTE_COUNT {len(multi)}",
        "",
    ]

    # ascii_map[128]: id or 255
    out.append("const uint8_t ascii_to_id[128] = {")
    for i in range(0, 128, 16):
        out.append("    " + ", ".join(str(v) for v in ascii_map[i : i + 16]) + ",")
    out.append("};")
    out.append("")

    # Multi-byte entries, packed
    max_len = max((len(b) for _, b in multi), default=1)
    out.append("typedef struct {")
    out.append("    uint8_t id;")
    out.append("    uint8_t len;")
    out.append(f"    uint8_t bytes[{max_len}];")
    out.append("} MultiByteEntry;")
    out.append("")
    out.append(f"const MultiByteEntry multi_byte_table[MULTI_BYTE_COUNT] = {{")
    for tid, b in multi:
        padded = list(b) + [0] * (max_len - len(b))
        out.append(
            "    { "
            + f"{tid}, {len(b)}, {{ "
            + ", ".join(f"0x{x:02x}" for x in padded)
            + " } },"
        )
    out.append("};")
    out.append("")

    # Reverse map: id -> NUL-terminated UTF-8 string
    out.append(f"const char *const id_to_utf8[{len(chars)}] = {{")
    for i, ch in enumerate(chars):
        b = ch.encode("utf-8")
        esc = "".join(f"\\x{x:02x}" for x in b)
        out.append(f'    "{esc}", /* id {i}: U+{ord(ch):04X} */')
    out.append("};")
    out.append("")

    out.append("#endif /* TOKENIZER_DATA_H */")
    return "\n".join(out) + "\n"


def build_config_header():
    return (
        "/* Auto-generated by tools/quantize.py -- do not edit. */\n"
        "#ifndef MODEL_CONFIG_H\n"
        "#define MODEL_CONFIG_H\n\n"
        f"#define VOCAB_SIZE      {VOCAB_SIZE}\n"
        f"#define CONTEXT_LENGTH  {CONTEXT_LENGTH}\n"
        f"#define EMBED_DIM       {EMBED_DIM}\n"
        f"#define NUM_HEADS       {NUM_HEADS}\n"
        f"#define HEAD_DIM        {HEAD_DIM}\n"
        f"#define FF_DIM          {FF_DIM}\n"
        "#define NUM_LAYERS      2\n\n"
        "#endif /* MODEL_CONFIG_H */\n"
    )


def main():
    if not WEIGHTS_PATH.exists():
        sys.exit(f"missing weights file: {WEIGHTS_PATH}")
    if not CORPUS_PATH.exists():
        sys.exit(f"missing corpus file: {CORPUS_PATH}")

    print(f"loading weights from {WEIGHTS_PATH}")
    state = torch.load(WEIGHTS_PATH, map_location="cpu")

    print(f"building char set from {CORPUS_PATH}")
    with open(CORPUS_PATH, "r", encoding="utf-8") as f:
        chars = sorted(list(set(f.read())))
    assert len(chars) == VOCAB_SIZE, (
        f"vocab size mismatch: header expects {VOCAB_SIZE}, got {len(chars)}"
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    (OUT_DIR / "model_config.h").write_text(build_config_header())
    print(f"  wrote {OUT_DIR / 'model_config.h'}")

    (OUT_DIR / "model_weights.h").write_text(build_weights_header(state))
    print(f"  wrote {OUT_DIR / 'model_weights.h'}")

    (OUT_DIR / "tokenizer_data.h").write_text(build_tokenizer_header(chars))
    print(f"  wrote {OUT_DIR / 'tokenizer_data.h'}")

    # Report footprint so we can sanity-check against the STM32F411 512 KB flash.
    total_int8 = 0
    total_float = 0
    for k, v in state.items():
        n = v.numel()
        if k.endswith(".weight") and v.ndim == 2:
            total_int8 += n
        else:
            total_float += n
    print(
        f"footprint: {total_int8} int8 bytes + {total_float} floats "
        f"= {total_int8 + total_float * 4} bytes flash"
    )


if __name__ == "__main__":
    main()
