/*
 * Character-level tokenizer for the 98-entry TinyStories vocabulary. Uses a
 * 128-entry direct table for ASCII (99% of inputs) and a tiny linear scan
 * over 14 multi-byte UTF-8 entries for the rest.
 *
 * The tables are auto-generated by tools/quantize.py.
 */

#include "tokenizer.h"

#include <string.h>

#include "../generated/tokenizer_data.h"

/* utf8_len: how many bytes this UTF-8 sequence claims to be, based on the
 * leading byte. Returns 0 for illegal / continuation bytes. */
static uint8_t utf8_len(uint8_t b) {
    if (b < 0x80) return 1;
    if ((b & 0xE0) == 0xC0) return 2;
    if ((b & 0xF0) == 0xE0) return 3;
    if ((b & 0xF8) == 0xF0) return 4;
    return 0;
}

size_t tokenize(const char *src, uint8_t *dst, size_t dst_cap) {
    size_t n = 0;
    const uint8_t *p = (const uint8_t *)src;

    while (*p && n < dst_cap) {
        uint8_t lead = *p;

        if (lead < 0x80) {
            uint8_t id = ascii_to_id[lead];
            if (id != 255) dst[n++] = id;
            p++;
            continue;
        }

        uint8_t need = utf8_len(lead);
        if (need == 0) { p++; continue; }         /* malformed lead */

        /* Bounds check the full sequence before touching it. */
        for (uint8_t i = 1; i < need; i++) {
            if (p[i] == 0) { need = 0; break; }
        }
        if (need == 0) break;

        int found = 0;
        for (int e = 0; e < MULTI_BYTE_COUNT; e++) {
            const MultiByteEntry *m = &multi_byte_table[e];
            if (m->len != need) continue;
            if (memcmp(m->bytes, p, need) == 0) {
                dst[n++] = m->id;
                found = 1;
                break;
            }
        }
        (void)found; /* unknown chars are silently dropped */
        p += need;
    }

    return n;
}

size_t detokenize_one(uint8_t id, char *dst, size_t dst_cap) {
    if (dst_cap == 0) return 0;
    const char *s = (id < VOCAB_SIZE) ? id_to_utf8[id] : "?";
    size_t len = strlen(s);
    if (len + 1 > dst_cap) len = dst_cap - 1;
    memcpy(dst, s, len);
    dst[len] = '\0';
    return len;
}
